---
title: "individual2.Rmd"
author: "Mike Brown"
date: "3/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part one: Cleaning Data

Although the three Excel sheets are loaded into R, they are not useful before
some cleaning. Manipulate the three imported data frames, so that in the cleaned dataset:

1.The player names and opponent names are factors.

  Answer:
  
2.All offensive and defensive statistics are numerical. The `Weight` column in biography is also numeric. (Optional: Read `?across` and learn to mutate multiple columns simultaneously using the `across` function in `dplyr`)

  Answer:
  
3.Change the `Height` column in biography into numeric. (Hint: Use a unit that works well)

  Answer:
  

## Part two: Tidying

For the following questions, work on the cleaned data frames `defClean`, `offClean`, and `bioClean`.

1.Reformat the `offClean` data frame into a tidy format using `pivot_longer`. The type of statistic (Receiving_REC for the number of receivings, Receiving_YDS for receiving yards) is added as a new key column named `stat`.

  Answer:
  
2.Show on the distributions of the offensive statistics. The distribution of each offensive statistic should be shown in a separate facet. Explain the patterns you see.

  Answer:
  
3.Did ISU have better offensive against Oregon or Oklahoma? Answer this question by creating a scatterplot with the x- and y-axes being the receiving yards of the ISU players against these two opponents. A large number of receiving yards indicates good offense.

  Answer:
  
Now turn our attention to the player biography.

4.Separate the `Hometown` column into two columns, namely, the city and the state where the player comes from. Print the fiers twe rows of these two columns. (Hint: look at the `sep=` argument of `separate`)

  Answer:
  
5.How many players are there from each state?

  Answer:
  

## Part three: Joining data frames

1.Find which states do the ISU players (both defensive and offensive) come from. Create an appropriate numerical or graphical summary.

  Answer:
  
2.How does the performance of quarterback Brock Purdy relate to the performance of the ISU team?

  Answer:
  
3.Which ISU player(s) made the biggest progress over the last year? Compare the player-level statistics (i.e. averages and totals for each player) using both the 2020 and the 2019 data here. Choose for yourself the player statistics to investigate.

  Answer:
